# Generated by Django 5.1.1 on 2024-10-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='points_earned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
