# Generated by Django 5.1.1 on 2024-10-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0002_customer_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(default="defaultpassword", max_length=128),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
